import { db, auth, signInAnonymously } from "./firebase.js";
import { ref, runTransaction, update } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js";
import { CONFIG } from "./config.js";

const nums = [...new Set(JSON.parse(localStorage.getItem("rifaSelecionados") || "[]"))].map(n => String(n).padStart(3, "0")).filter(n => /^\d{3}$/.test(n) && Number(n) <= 999);
const numsEl=document.getElementById("confirmacaoNumeros"), valorEl=document.getElementById("confirmacaoValor"), dataEl=document.getElementById("confirmacaoData"), horaEl=document.getElementById("confirmacaoHora");
const nomeEl=document.getElementById("nome"), foneEl=document.getElementById("fone"), btn=document.getElementById("confirmar"), msg=document.getElementById("mensagemPix"), pixEl=document.getElementById("pixChave"), statusEl=document.getElementById("statusReserva"), acoesEl=document.getElementById("acoesComprovante");
const reservaExistente=localStorage.getItem("rifaReservaId");

function formatarMoeda(v){return Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}
function mostrarDados(agora=Number(localStorage.getItem("rifaReservaCriadaEm")||Date.now())){numsEl.textContent=nums.length?nums.join(", "):"Nenhum número selecionado";valorEl.textContent=nums.length?`${nums.length} número(s) • Total: ${formatarMoeda(nums.length*Number(CONFIG.valor||10))}`:"R$ 0,00";const d=new Date(agora);dataEl.textContent=d.toLocaleDateString("pt-BR");horaEl.textContent=d.toLocaleTimeString("pt-BR");pixEl.textContent=CONFIG.pix||"045.761.515-09"}
function mostrarMensagem(t,erro=false){msg.textContent=t;msg.style.color=erro?"#a3002e":"#087b25"}
function gerarIdReserva(){return crypto.randomUUID?crypto.randomUUID():`res-${Date.now()}-${Math.random().toString(36).slice(2,10)}`}
function normalizarTelefone(v){return v.replace(/\D/g,"")}
async function garantirAutenticacao(){if(auth.currentUser)return auth.currentUser;return (await signInAnonymously(auth)).user}
async function liberarNumero(numero,uid){const r=ref(db,`rifa/numeros/${numero}`);await runTransaction(r,a=>{if(!a||a.participanteId!==uid||a.status!=="reservado")return;return {...a,status:"disponivel",nome:"",telefone:"",pagamento:false,participanteId:"",reservaId:"",criadoEm:"",expiraEm:""}})}
function mostrarPosReserva(reservaId,agora){statusEl.hidden=false;statusEl.innerHTML=`<strong>✅ RESERVA CONFIRMADA</strong><br>Reserva: <b>${reservaId}</b><br>Seus números estão reservados por 30 minutos.<br>Agora faça o PIX e envie o comprovante.`;acoesEl.hidden=false;btn.style.display="none";nomeEl.disabled=true;foneEl.disabled=true;document.getElementById("limparNumeros").style.display="none";mostrarDados(agora)}
async function reservar(){const nome=nomeEl.value.trim(),telefone=normalizarTelefone(foneEl.value);if(!nome||telefone.length<10||!nums.length){mostrarMensagem("Preencha seu nome, um WhatsApp válido e selecione pelo menos um número.",true);return}btn.disabled=true;btn.textContent="RESERVANDO...";mostrarMensagem("Aguarde. Estamos verificando os números...");const adquiridos=[];let uid=null;try{const user=await garantirAutenticacao();uid=user.uid;const agora=Date.now(),expiraEm=agora+30*60*1000,reservaId=gerarIdReserva();for(const numero of nums){const numeroRef=ref(db,`rifa/numeros/${numero}`);const resultado=await runTransaction(numeroRef,atual=>{const expirado=atual?.status==="reservado"&&Number(atual.expiraEm||0)<=Date.now();if(!atual)return;if(atual.status==="disponivel"||expirado)return {...atual,numero,status:"reservado",nome,telefone,pagamento:false,pagamentoStatus:"aguardando_comprovante",participanteId:uid,reservaId,criadoEm:agora,expiraEm,comprovanteEnviado:false,raspadinhaLiberada:false};return});if(!resultado.committed)throw new Error(`O número ${numero} acabou de ser reservado por outra pessoa.`);adquiridos.push(numero)}await update(ref(db,`rifa/reservas/${reservaId}`),{reservaId,participanteId:uid,nome,telefone,numeros:adquiridos,quantidade:adquiridos.length,valorUnitario:CONFIG.valor,valorTotal:adquiridos.length*CONFIG.valor,status:"reservado",pagamentoStatus:"aguardando_comprovante",pagamento:false,comprovanteEnviado:false,raspadinhaLiberada:false,criadoEm:agora,expiraEm});localStorage.setItem("rifaReservaId",reservaId);localStorage.setItem("rifaParticipanteId",uid);localStorage.setItem("rifaSelecionados",JSON.stringify(adquiridos));localStorage.setItem("rifaReservaCriadaEm",String(agora));mostrarPosReserva(reservaId,agora)}catch(erro){console.error(erro);if(uid&&adquiridos.length)await Promise.allSettled(adquiridos.map(n=>liberarNumero(n,uid)));let m=erro?.message||"Não foi possível concluir a reserva.";if(erro?.code==="PERMISSION_DENIED")m="O Firebase recusou a reserva. Verifique o login anônimo e as regras.";if(erro?.code==="auth/operation-not-allowed")m="O login anônimo ainda não está ativado no Firebase Authentication.";mostrarMensagem(m,true)}finally{if(!statusEl.hidden){btn.disabled=true}else{btn.disabled=false;btn.textContent="CONFIRMAR RESERVA"}}}

btn.addEventListener("click",reservar);
document.getElementById("limparNumeros")?.addEventListener("click",()=>{localStorage.removeItem("rifaSelecionados");localStorage.removeItem("rifaReservaId");localStorage.removeItem("rifaReservaCriadaEm");location.href="cartela.html"});
document.getElementById("copiarPix")?.addEventListener("click",async()=>{const pix=CONFIG.pix||"045.761.515-09";try{await navigator.clipboard.writeText(pix);mostrarMensagem("✅ PIX copiado!")}catch{mostrarMensagem(`Chave PIX: ${pix}`)}});
document.getElementById("enviarComprovante")?.addEventListener("click",()=>{const id=localStorage.getItem("rifaReservaId")||"";location.href=`comprovante.html${id?`?reservaId=${encodeURIComponent(id)}`:""}`});

mostrarDados();
if(reservaExistente){mostrarPosReserva(reservaExistente,Number(localStorage.getItem("rifaReservaCriadaEm")||Date.now()))}
if(!nums.length){btn.disabled=true;mostrarMensagem("Volte para a cartela e escolha pelo menos um número.",true)}
